#!/bin/bash

docker run -it --rm --user "$(id -u):$(id -g)" -v "$(pwd):/app" -w /app -e COMPOSER_HOME=/tmp/composer laravelsail/php84-composer:latest bash -c "composer global require laravel/installer && /tmp/composer/vendor/bin/laravel new $1"